server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html/webshop-pro;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /webshop-lab/ {
        alias /usr/share/nginx/html/webshop-lab/;
        try_files $uri $uri/ /webshop-lab/index.html;
    }

    location /webshop-lab {
        return 301 /webshop-lab/;
    }
}
